[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
force_single_line = true
known_third_party = ["matplotlib", "munch", "numpy", "pandas", "pygal", "requests", "scipy", "shapely", "pytz", "typing_extensions"]
known_first_party = ["viktor"]
skip_glob = [".env"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "C0111",
    "E0611",
    "R0801",
    "R0201",
    "C0301",
    "C0302",
    "C0103",
    "R0903",
    "R1705",
    "E0401",
    "R0914",
    "W0511",
    "R0913",
    "R0912",
    "W0613",
    "C0326",
    "C0330",
    "R0401",
    "W0707",
    "C0411",
    "R0902",
    "W0105",
    "W0640",
    "R0904"
]
